# Generated by Django 2.0.5 on 2018-05-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0002_auto_20180505_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
