# Generated by Django 2.0.5 on 2018-05-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0003_remove_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='post_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='askit.Question'),
        ),
    ]
