# Generated by Django 2.0.5 on 2018-05-14 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0004_auto_20180511_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 2, 50, 16, 801552, tzinfo=utc)),
        ),
    ]
