# Generated by Django 2.0.5 on 2018-05-14 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0005_auto_20180514_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 4, 1, 43, 224522, tzinfo=utc)),
        ),
    ]
